/**
 * Client data structures & helper methods for all 28 States and 8 Union Territories of India.
 * Mirrors apps/api/app/ingestion/all_states.py.
 */

export interface StateSummary {
  iso_code: string;
  lgd_code: number;
  name_en: string;
  name_native: string;
  native_language: string;
  official_languages: string[];
  category: "state" | "union_territory";
  capital: string;
  assembly_seats: number;
  parliamentary_seats: number;
  official_website: string;
}

/** Sentinel jurisdiction for the national (all States & UTs) view. */
export const ALL_INDIA_ISO = "IN-ALL";

/** Synthetic summary used when the site-wide selector is set to All India. */
export const ALL_INDIA_SUMMARY: StateSummary = {
  iso_code: ALL_INDIA_ISO,
  lgd_code: 0,
  name_en: "All India",
  name_native: "भारत",
  native_language: "hi",
  official_languages: [],
  category: "state",
  capital: "New Delhi",
  assembly_seats: 0,
  parliamentary_seats: 543,
  official_website: "https://www.india.gov.in",
};

type StateRow = [
  iso_code: string,
  lgd_code: number,
  name_en: string,
  name_native: string,
  native_language: string,
  official_languages: string[],
  category: "state" | "union_territory",
  capital: string,
  assembly_seats: number,
  parliamentary_seats: number,
  official_website: string,
];

const STATE_ROWS: StateRow[] = [
  // 28 STATES
  [
    "IN-AP",
    28,
    "Andhra Pradesh",
    "ఆంధ్రప్రదేశ్",
    "te",
    ["te", "en"],
    "state",
    "Amaravati",
    175,
    25,
    "https://ap.gov.in",
  ],
  [
    "IN-AR",
    12,
    "Arunachal Pradesh",
    "अरुणाचल प्रदेश",
    "hi",
    ["en"],
    "state",
    "Itanagar",
    60,
    2,
    "https://arunachalpradesh.gov.in",
  ],
  [
    "IN-AS",
    18,
    "Assam",
    "অসম",
    "as",
    ["as", "bn", "brx", "en"],
    "state",
    "Dispur",
    126,
    14,
    "https://assam.gov.in",
  ],
  [
    "IN-BR",
    10,
    "Bihar",
    "बिहार",
    "hi",
    ["hi", "ur"],
    "state",
    "Patna",
    243,
    40,
    "https://bihar.gov.in",
  ],
  [
    "IN-CT",
    22,
    "Chhattisgarh",
    "छत्तीसगढ़",
    "hi",
    ["hi"],
    "state",
    "Raipur",
    90,
    11,
    "https://cgstate.gov.in",
  ],
  [
    "IN-GA",
    30,
    "Goa",
    "गोवा",
    "kok",
    ["kok", "mr", "en"],
    "state",
    "Panaji",
    40,
    2,
    "https://goa.gov.in",
  ],
  [
    "IN-GJ",
    24,
    "Gujarat",
    "ગુજરાત",
    "gu",
    ["gu", "en"],
    "state",
    "Gandhinagar",
    182,
    26,
    "https://gujaratindia.gov.in",
  ],
  [
    "IN-HR",
    6,
    "Haryana",
    "हरियाणा",
    "hi",
    ["hi", "pa"],
    "state",
    "Chandigarh",
    90,
    10,
    "https://haryana.gov.in",
  ],
  [
    "IN-HP",
    2,
    "Himachal Pradesh",
    "हिमाचल प्रदेश",
    "hi",
    ["hi"],
    "state",
    "Shimla",
    68,
    4,
    "https://himachal.nic.in",
  ],
  [
    "IN-JH",
    20,
    "Jharkhand",
    "झारखंड",
    "hi",
    ["hi"],
    "state",
    "Ranchi",
    81,
    14,
    "https://jharkhand.gov.in",
  ],
  [
    "IN-KA",
    29,
    "Karnataka",
    "ಕರ್ನಾಟಕ",
    "kn",
    ["kn", "en"],
    "state",
    "Bengaluru",
    224,
    28,
    "https://karnataka.gov.in",
  ],
  [
    "IN-KL",
    32,
    "Kerala",
    "കേരളം",
    "ml",
    ["ml", "en"],
    "state",
    "Thiruvananthapuram",
    140,
    20,
    "https://kerala.gov.in",
  ],
  [
    "IN-MP",
    23,
    "Madhya Pradesh",
    "मध्य प्रदेश",
    "hi",
    ["hi"],
    "state",
    "Bhopal",
    230,
    29,
    "https://mp.gov.in",
  ],
  [
    "IN-MH",
    27,
    "Maharashtra",
    "महाराष्ट्र",
    "mr",
    ["mr", "hi"],
    "state",
    "Mumbai",
    288,
    48,
    "https://maharashtra.gov.in",
  ],
  [
    "IN-MN",
    14,
    "Manipur",
    "মণিপুর",
    "mni",
    ["mni", "en"],
    "state",
    "Imphal",
    60,
    2,
    "https://manipur.gov.in",
  ],
  [
    "IN-ML",
    17,
    "Meghalaya",
    "Meghalaya",
    "en",
    ["en"],
    "state",
    "Shillong",
    60,
    2,
    "https://meghalaya.gov.in",
  ],
  [
    "IN-MZ",
    15,
    "Mizoram",
    "Mizoram",
    "mzo",
    ["mzo", "en"],
    "state",
    "Aizawl",
    40,
    1,
    "https://mizoram.gov.in",
  ],
  [
    "IN-NL",
    13,
    "Nagaland",
    "Nagaland",
    "en",
    ["en"],
    "state",
    "Kohima",
    60,
    1,
    "https://nagaland.gov.in",
  ],
  [
    "IN-OR",
    21,
    "Odisha",
    "ଓଡ଼ିଶା",
    "or",
    ["or"],
    "state",
    "Bhubaneswar",
    147,
    21,
    "https://odisha.gov.in",
  ],
  [
    "IN-PB",
    3,
    "Punjab",
    "ਪੰਜਾਬ",
    "pa",
    ["pa"],
    "state",
    "Chandigarh",
    117,
    13,
    "https://punjab.gov.in",
  ],
  [
    "IN-RJ",
    8,
    "Rajasthan",
    "राजस्थान",
    "hi",
    ["hi"],
    "state",
    "Jaipur",
    200,
    25,
    "https://rajasthan.gov.in",
  ],
  [
    "IN-SK",
    11,
    "Sikkim",
    "सिक्किम",
    "ne",
    ["ne", "en", "hi"],
    "state",
    "Gangtok",
    32,
    1,
    "https://sikkim.gov.in",
  ],
  [
    "IN-TN",
    33,
    "Tamil Nadu",
    "தமிழ்நாடு",
    "ta",
    ["ta", "en"],
    "state",
    "Chennai",
    234,
    39,
    "https://tn.gov.in",
  ],
  [
    "IN-TG",
    36,
    "Telangana",
    "తెలంగాణ",
    "te",
    ["te", "ur"],
    "state",
    "Hyderabad",
    119,
    17,
    "https://telangana.gov.in",
  ],
  [
    "IN-TR",
    16,
    "Tripura",
    "ত্রিপুরা",
    "bn",
    ["bn", "en"],
    "state",
    "Agartala",
    60,
    2,
    "https://tripura.gov.in",
  ],
  [
    "IN-UP",
    9,
    "Uttar Pradesh",
    "उत्तर प्रदेश",
    "hi",
    ["hi", "ur"],
    "state",
    "Lucknow",
    403,
    80,
    "https://up.gov.in",
  ],
  [
    "IN-UT",
    5,
    "Uttarakhand",
    "उत्तराखंड",
    "hi",
    ["hi", "sa"],
    "state",
    "Dehradun",
    70,
    5,
    "https://uk.gov.in",
  ],
  [
    "IN-WB",
    19,
    "West Bengal",
    "পশ্চিমবঙ্গ",
    "bn",
    ["bn", "en"],
    "state",
    "Kolkata",
    294,
    42,
    "https://wb.gov.in",
  ],
  // 8 UNION TERRITORIES
  [
    "IN-AN",
    35,
    "Andaman and Nicobar Islands",
    "अंडमान और निकोबार",
    "hi",
    ["hi", "en"],
    "union_territory",
    "Port Blair",
    0,
    1,
    "https://andaman.gov.in",
  ],
  [
    "IN-CH",
    4,
    "Chandigarh",
    "चंडीगढ़",
    "hi",
    ["en", "hi", "pa"],
    "union_territory",
    "Chandigarh",
    0,
    1,
    "https://chandigarh.gov.in",
  ],
  [
    "IN-DH",
    26,
    "Dadra & Nagar Haveli & Daman & Diu",
    "दादरा नगर हवेली",
    "hi",
    ["gu", "hi"],
    "union_territory",
    "Daman",
    0,
    1,
    "https://daman.nic.in",
  ],
  [
    "IN-DL",
    7,
    "Delhi (NCT)",
    "दिल्ली",
    "hi",
    ["hi", "en", "ur", "pa"],
    "union_territory",
    "New Delhi",
    70,
    7,
    "https://delhi.gov.in",
  ],
  [
    "IN-JK",
    1,
    "Jammu & Kashmir",
    "जम्मू-कश्मीर",
    "hi",
    ["hi", "ur", "en", "ks", "doi"],
    "union_territory",
    "Srinagar/Jammu",
    90,
    5,
    "https://jk.gov.in",
  ],
  [
    "IN-LA",
    37,
    "Ladakh",
    "लद्दाख",
    "hi",
    ["hi", "en"],
    "union_territory",
    "Leh/Kargil",
    0,
    1,
    "https://ladakh.gov.in",
  ],
  [
    "IN-LD",
    31,
    "Lakshadweep",
    "ലക്ഷദ്വീപ്",
    "ml",
    ["ml"],
    "union_territory",
    "Kavaratti",
    0,
    1,
    "https://lakshadweep.gov.in",
  ],
  [
    "IN-PY",
    34,
    "Puducherry",
    "புதுச்சேரி",
    "ta",
    ["ta", "ml", "te", "en"],
    "union_territory",
    "Puducherry",
    30,
    1,
    "https://puducherry.gov.in",
  ],
];

export const ALL_INDIA_STATES_UTS_DATA: StateSummary[] = STATE_ROWS.map(
  ([
    iso_code,
    lgd_code,
    name_en,
    name_native,
    native_language,
    official_languages,
    category,
    capital,
    assembly_seats,
    parliamentary_seats,
    official_website,
  ]) => ({
    iso_code,
    lgd_code,
    name_en,
    name_native,
    native_language,
    official_languages,
    category,
    capital,
    assembly_seats,
    parliamentary_seats,
    official_website,
  }),
);

export function getStateByIsoCode(isoCode: string): StateSummary | undefined {
  if (isoCode.toLowerCase() === ALL_INDIA_ISO.toLowerCase()) {
    return ALL_INDIA_SUMMARY;
  }
  return ALL_INDIA_STATES_UTS_DATA.find(
    (s) => s.iso_code.toLowerCase() === isoCode.toLowerCase(),
  );
}
